# https://github.com/utilitywarehouse/customer-tracking-sdk

CODE_FSPATH=$(PWD)/customer-tracking-sdk

print:
	@echo hey
dep:
	git clone https://github.com/utilitywarehouse/customer-tracking-sdk

run:
	cd $(CODE_FSPATH)/examples/go && go run .